version: '3.3'
services:
  dmgr:
    image: wasnd855-dmgr:centos7
    build:
      context: ./dmgr
      dockerfile: centos7.Dockerfile
    ports:
     - "9060:9060"

  custom1:
    image: wasnd855-custom:centos7
    build:
      context: ./custom
      dockerfile: centos7.Dockerfile
    ports:
     - "9080:9080"
    environment:
     - PROFILE_NAME=custom
     - HOST_NAME=custom1
     - NODE_NAME=custom1
     - DMGR_HOST=dmgr
     - DMGR_PORT=8879
    depends_on:
     - dmgr

  custom2:
    image: wasnd855-custom:centos7
    command: /work/updateHostAndAdd2nNode.sh
    ports:
     - "9081:9080"
    environment:
     - PROFILE_NAME=custom
     - HOST_NAME=custom2
     - NODE_NAME=custom2
     - DMGR_HOST=dmgr
     - DMGR_PORT=8879
    depends_on:
     - custom1
